### ISSUE TITLE
Shield\Session::write and Shield\Session::read need to test

### ISSUE THREAD

**Issue by rpecb** [enygma/shieldframework#12]
I copied your code and it did not work.

Mistake is that the $iv for reading should be the same as for the record, but now it is generated each time a different.

I implemented encryption as follows:

``` php
<?php

public static function encrypt($data)
{
    $ivSize = mcrypt_get_iv_size(MCRYPT_RIJNDAEL_256, MCRYPT_MODE_CBC);
    $iv = mcrypt_create_iv($ivSize, MCRYPT_RAND);
    $keySize = mcrypt_get_key_size(MCRYPT_RIJNDAEL_256, MCRYPT_MODE_CBC);

    return base64_encode($iv.mcrypt_encrypt( // store $iv along with the data
        MCRYPT_RIJNDAEL_256,
        substr(sha1(self::$encryptionKey), 0, $keySize), //  self::$encryptionKey - "Salt for hashing the session data"
        $data,
        MCRYPT_MODE_CBC,
        $iv
    ));
}

public static function decrypt($data)
{
    $data = base64_decode($data, true);
    if (!$data) {
        return false;
    }

    $ivSize = mcrypt_get_iv_size(MCRYPT_RIJNDAEL_256, MCRYPT_MODE_CBC);
    $iv = substr($data, 0, $ivSize); // get $iv back

    if ($ivSize !== strlen($iv)) {
        return false;
    }

    $keySize = mcrypt_get_key_size(MCRYPT_RIJNDAEL_256, MCRYPT_MODE_CBC);
    $data = substr($data, $ivSize); // remove $iv from data

    return rtrim(mcrypt_decrypt( // decrypt our data using $iv they were encoding
        MCRYPT_RIJNDAEL_256,
        substr(sha1(self::$encryptionKey), 0, $keySize),
        $data,
        MCRYPT_MODE_CBC,
        $iv
    ), "\0");
}
```

Made based on the [Kohana_Encrypt class](https://github.com/kohana/core/blob/3.2/master/classes/kohana/encrypt.php) code 

Sorry for my bad english.

**Comment by enygma** [comment]
Storing the IV along with the encrypted data seems a little insecure to me - especially if it's only base64 encoded and stuck on the front. Have you seen any other implementations of this?

**Comment by rpecb** [comment]
No. In [Yii](https://github.com/yiisoft/yii/blob/master/framework/base/CSecurityManager.php), [Laravel](https://github.com/laravel/laravel/blob/master/laravel/crypter.php), [Zend](https://github.com/zendframework/zf2/blob/master/library/Zend/Crypt/BlockCipher.php) IV is stored with the data, in [CakePHP](https://github.com/cakephp/cakephp/blob/master/lib/Cake/Utility/Security.php) IV based on encryption key (substring). In plugin for Symfony [dwCryptPlugin](http://trac.symfony-project.org/browser/plugins/dwCryptPlugin/lib/sfCrypt.class.php) a slightly different way.

**Comment by enygma** [comment]
Works for me...just implemented this same practice: https://github.com/enygma/shieldframework/commit/5d99bedaa5aa7933211938fae4244e04645950b5
