### ISSUE TITLE
Missing required param

### ISSUE THREAD

**Issue by Jasrags** [enygma/shieldframework#2]
File: Shield.php line 65

$filter = new Filter($this->di);

Filter expects a $value param as well, i would fix this but i have no idea what you want to pass if anything.

**Comment by enygma** [comment]
There's a filter() method on the Filter object - is that what you're seeing? What's the actual error being thrown?

**Comment by Jasrags** [comment]
Wow, the IDE is interpreting the function filter as the constructor for the Filter object when you call

$filter = new Filter($this->di);

and the filter method is 

public function filter($name, $value)

Is this the intended effect?

**Comment by Jasrags** [comment]
Looks like just missing the constructor like Input has to load in the di

**Comment by enygma** [comment]
This has been corrected in this commit: https://github.com/enygma/shieldframework/commit/c7f9144cc49937821ee5b8af54bdd3eabc98ca16
